apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: fastapi-monitor
  namespace: ollamahub
  labels:
    release: prometheus

spec:
  selector:
    matchLabels:
      app: backend-deployment-label
  endpoints:
    - port: http
      path: /metrics
      interval: 15s  