apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: ollamahub
  labels:
    app: backend-deployment-label

spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-deployment-label

  template:
    metadata:
      labels:
        app: backend-deployment-label

    spec:
      containers:
      - name: myapp
        image: qais001/ai-hub:02

        ports:
        - containerPort: 8000

        resources:
          requests:
            cpu: "500m"
            memory: "128Mi"
          limits:
            cpu: "1"
            memory: "500Mi"
            
        startupProbe:
          httpGet:
            path: /healthz
            port: 8000
          failureThreshold: 30
          periodSeconds: 5

        livenessProbe:
          httpGet:
            path: /healthz
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 2
          failureThreshold: 3

        readinessProbe:
          httpGet:
            path: /ready
            port: 8000
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 2
          failureThreshold: 3

        
        envFrom:
        - configMapRef:
            name: backend-configmap