apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app
  namespace: ollamahub
  labels:
    app: web-app-deployments
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-app-deployments
  template:
    metadata:
      name: web-app
      labels: 
        app: web-app-deployments
    spec:
      containers:
      - name: web-app-container
        image: qais001/ai-hub-web-app:03
        envFrom:
        - configMapRef:
            name: web-app-config-map
        resources:
          requests:
            cpu: "500m"
            memory: "256Mi"
          limits:
            cpu: "1"
            memory: "500Mi"
        ports:
        - containerPort: 80
        
      