apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ollama-ingress
  namespace: ollamahub
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: selfsigned-issuer
spec:
  ingressClassName: nginx
  
  tls:
  - hosts:
    - ollama.ai.com
    secretName: demo-tls
  
  rules:
  - host: ollama.ai.com
    http:
      paths:

      - pathType: Prefix
        path: /
        backend:
          service:
            name: web-app-service
            port: 
              number: 80
      
      - pathType: Prefix
        path: /api
        backend:
          service:
            name: backend-service
            port: 
              number: 8000
