apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ollamahub-pvc
  namespace: ollamahub
  labels:
    app: ollama
spec:
  resources:
    requests:
      storage: "15Gi"
  accessModes: 
  - ReadWriteOnce
  storageClassName: standard