apiVersion: v1
kind: Service
metadata:
  name: ollamahub-service
  namespace: ollamahub
  labels:
    app: ollama
spec:
  selector:
    app: ollama
  ports:
  - name: ollmahub-service
    port: 11434
    targetPort: 11434
  type: ClusterIP