apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgress-deployment
  namespace: ollamahub
spec:
  selector:
    matchLabels:
      app: postgress-deployment
  template:
    metadata:
      labels:
        app: postgress-deployment
    spec:
      containers:
      - name: postgress-container
        image: postgres:alpine
        ports:
        - containerPort: 5432
        resources:
          requests:
            cpu: "250m"
            memory: "256Mi"
          limits:
            cpu: "1"
            memory: "1Gi"
        envFrom:
        -  configMapRef:
             name: postgres-configmap
        volumeMounts:
        - name: postgres-pv
          mountPath: /var/lib/postgresql
        
      volumes:
      - name: postgres-pv
        persistentVolumeClaim: 
          claimName: postgres-pvc
