apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: ollamahub
spec:
  resources:
    requests:
      storage: 10Gi
  volumeMode: Filesystem
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  
